/* soapCRAB_ProxySOAPProxy.h
   Generated by gSOAP 2.7.9l from CRAB-Proxy.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapCRAB_ProxySOAPProxy_H
#define soapCRAB_ProxySOAPProxy_H
#include "soapH.h"

class SOAP_CMAC CRAB_ProxySOAPProxy : public soap
{ public:
	/// Endpoint URL of service 'CRAB_ProxySOAPProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	CRAB_ProxySOAPProxy();
	/// Constructor with engine input+output mode control
	CRAB_ProxySOAPProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	CRAB_ProxySOAPProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~CRAB_ProxySOAPProxy();
	/// Initializer used by constructor
	virtual	void CRAB_ProxySOAPProxy_init(soap_mode imode, soap_mode omode);
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();

	/// Web service operation 'transferTaskAndSubmit' (return error code or SOAP_OK)
	virtual	int transferTaskAndSubmit(ns1__transferTaskType *transferTaskAndSubmitRequest, struct ns1__transferTaskAndSubmitResponse &_param_1);
	/// Web service operation 'sendCommand' (return error code or SOAP_OK)
	virtual	int sendCommand(ns1__sendCommandType *sendCommandRequest, struct ns1__sendCommandResponse &_param_2);
	/// Web service operation 'getTaskStatus' (return error code or SOAP_OK)
	virtual	int getTaskStatus(ns1__getTaskStatusType *getTaskStatusRequest, struct ns1__getTaskStatusResponse &_param_3);
};
#endif
