/* soapH.h
   Generated by gSOAP 2.7.9l from CRAB-Proxy.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_ns1__sendCommandType
#define SOAP_TYPE_ns1__sendCommandType (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendCommandType(struct soap*, const char*, int, const ns1__sendCommandType *, const char*);
SOAP_FMAC3 ns1__sendCommandType * SOAP_FMAC4 soap_get_ns1__sendCommandType(struct soap*, ns1__sendCommandType *, const char*, const char*);
SOAP_FMAC3 ns1__sendCommandType * SOAP_FMAC4 soap_in_ns1__sendCommandType(struct soap*, const char*, ns1__sendCommandType *, const char*);
SOAP_FMAC5 ns1__sendCommandType * SOAP_FMAC6 soap_new_ns1__sendCommandType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendCommandType(struct soap*, ns1__sendCommandType*);
SOAP_FMAC3 ns1__sendCommandType * SOAP_FMAC4 soap_instantiate_ns1__sendCommandType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendCommandType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__transferTaskType
#define SOAP_TYPE_ns1__transferTaskType (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__transferTaskType(struct soap*, const char*, int, const ns1__transferTaskType *, const char*);
SOAP_FMAC3 ns1__transferTaskType * SOAP_FMAC4 soap_get_ns1__transferTaskType(struct soap*, ns1__transferTaskType *, const char*, const char*);
SOAP_FMAC3 ns1__transferTaskType * SOAP_FMAC4 soap_in_ns1__transferTaskType(struct soap*, const char*, ns1__transferTaskType *, const char*);
SOAP_FMAC5 ns1__transferTaskType * SOAP_FMAC6 soap_new_ns1__transferTaskType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__transferTaskType(struct soap*, ns1__transferTaskType*);
SOAP_FMAC3 ns1__transferTaskType * SOAP_FMAC4 soap_instantiate_ns1__transferTaskType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__transferTaskType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__getTaskStatus
#define SOAP_TYPE_ns1__getTaskStatus (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getTaskStatus(struct soap*, struct ns1__getTaskStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getTaskStatus(struct soap*, const struct ns1__getTaskStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getTaskStatus(struct soap*, const struct ns1__getTaskStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getTaskStatus(struct soap*, const char*, int, const struct ns1__getTaskStatus *, const char*);
SOAP_FMAC3 struct ns1__getTaskStatus * SOAP_FMAC4 soap_get_ns1__getTaskStatus(struct soap*, struct ns1__getTaskStatus *, const char*, const char*);
SOAP_FMAC3 struct ns1__getTaskStatus * SOAP_FMAC4 soap_in_ns1__getTaskStatus(struct soap*, const char*, struct ns1__getTaskStatus *, const char*);
SOAP_FMAC5 struct ns1__getTaskStatus * SOAP_FMAC6 soap_new_ns1__getTaskStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getTaskStatus(struct soap*, struct ns1__getTaskStatus*);
SOAP_FMAC3 struct ns1__getTaskStatus * SOAP_FMAC4 soap_instantiate_ns1__getTaskStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getTaskStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getTaskStatusResponse
#define SOAP_TYPE_ns1__getTaskStatusResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getTaskStatusResponse(struct soap*, struct ns1__getTaskStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getTaskStatusResponse(struct soap*, const struct ns1__getTaskStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getTaskStatusResponse(struct soap*, const struct ns1__getTaskStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getTaskStatusResponse(struct soap*, const char*, int, const struct ns1__getTaskStatusResponse *, const char*);
SOAP_FMAC3 struct ns1__getTaskStatusResponse * SOAP_FMAC4 soap_get_ns1__getTaskStatusResponse(struct soap*, struct ns1__getTaskStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getTaskStatusResponse * SOAP_FMAC4 soap_in_ns1__getTaskStatusResponse(struct soap*, const char*, struct ns1__getTaskStatusResponse *, const char*);
SOAP_FMAC5 struct ns1__getTaskStatusResponse * SOAP_FMAC6 soap_new_ns1__getTaskStatusResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getTaskStatusResponse(struct soap*, struct ns1__getTaskStatusResponse*);
SOAP_FMAC3 struct ns1__getTaskStatusResponse * SOAP_FMAC4 soap_instantiate_ns1__getTaskStatusResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getTaskStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__sendCommand
#define SOAP_TYPE_ns1__sendCommand (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sendCommand(struct soap*, struct ns1__sendCommand *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sendCommand(struct soap*, const struct ns1__sendCommand *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sendCommand(struct soap*, const struct ns1__sendCommand *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendCommand(struct soap*, const char*, int, const struct ns1__sendCommand *, const char*);
SOAP_FMAC3 struct ns1__sendCommand * SOAP_FMAC4 soap_get_ns1__sendCommand(struct soap*, struct ns1__sendCommand *, const char*, const char*);
SOAP_FMAC3 struct ns1__sendCommand * SOAP_FMAC4 soap_in_ns1__sendCommand(struct soap*, const char*, struct ns1__sendCommand *, const char*);
SOAP_FMAC5 struct ns1__sendCommand * SOAP_FMAC6 soap_new_ns1__sendCommand(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendCommand(struct soap*, struct ns1__sendCommand*);
SOAP_FMAC3 struct ns1__sendCommand * SOAP_FMAC4 soap_instantiate_ns1__sendCommand(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendCommand(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__sendCommandResponse
#define SOAP_TYPE_ns1__sendCommandResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sendCommandResponse(struct soap*, struct ns1__sendCommandResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sendCommandResponse(struct soap*, const struct ns1__sendCommandResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sendCommandResponse(struct soap*, const struct ns1__sendCommandResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendCommandResponse(struct soap*, const char*, int, const struct ns1__sendCommandResponse *, const char*);
SOAP_FMAC3 struct ns1__sendCommandResponse * SOAP_FMAC4 soap_get_ns1__sendCommandResponse(struct soap*, struct ns1__sendCommandResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__sendCommandResponse * SOAP_FMAC4 soap_in_ns1__sendCommandResponse(struct soap*, const char*, struct ns1__sendCommandResponse *, const char*);
SOAP_FMAC5 struct ns1__sendCommandResponse * SOAP_FMAC6 soap_new_ns1__sendCommandResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendCommandResponse(struct soap*, struct ns1__sendCommandResponse*);
SOAP_FMAC3 struct ns1__sendCommandResponse * SOAP_FMAC4 soap_instantiate_ns1__sendCommandResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendCommandResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__transferTaskAndSubmit
#define SOAP_TYPE_ns1__transferTaskAndSubmit (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__transferTaskAndSubmit(struct soap*, struct ns1__transferTaskAndSubmit *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__transferTaskAndSubmit(struct soap*, const struct ns1__transferTaskAndSubmit *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__transferTaskAndSubmit(struct soap*, const struct ns1__transferTaskAndSubmit *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__transferTaskAndSubmit(struct soap*, const char*, int, const struct ns1__transferTaskAndSubmit *, const char*);
SOAP_FMAC3 struct ns1__transferTaskAndSubmit * SOAP_FMAC4 soap_get_ns1__transferTaskAndSubmit(struct soap*, struct ns1__transferTaskAndSubmit *, const char*, const char*);
SOAP_FMAC3 struct ns1__transferTaskAndSubmit * SOAP_FMAC4 soap_in_ns1__transferTaskAndSubmit(struct soap*, const char*, struct ns1__transferTaskAndSubmit *, const char*);
SOAP_FMAC5 struct ns1__transferTaskAndSubmit * SOAP_FMAC6 soap_new_ns1__transferTaskAndSubmit(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__transferTaskAndSubmit(struct soap*, struct ns1__transferTaskAndSubmit*);
SOAP_FMAC3 struct ns1__transferTaskAndSubmit * SOAP_FMAC4 soap_instantiate_ns1__transferTaskAndSubmit(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__transferTaskAndSubmit(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__transferTaskAndSubmitResponse
#define SOAP_TYPE_ns1__transferTaskAndSubmitResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__transferTaskAndSubmitResponse(struct soap*, struct ns1__transferTaskAndSubmitResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__transferTaskAndSubmitResponse(struct soap*, const struct ns1__transferTaskAndSubmitResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__transferTaskAndSubmitResponse(struct soap*, const struct ns1__transferTaskAndSubmitResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__transferTaskAndSubmitResponse(struct soap*, const char*, int, const struct ns1__transferTaskAndSubmitResponse *, const char*);
SOAP_FMAC3 struct ns1__transferTaskAndSubmitResponse * SOAP_FMAC4 soap_get_ns1__transferTaskAndSubmitResponse(struct soap*, struct ns1__transferTaskAndSubmitResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__transferTaskAndSubmitResponse * SOAP_FMAC4 soap_in_ns1__transferTaskAndSubmitResponse(struct soap*, const char*, struct ns1__transferTaskAndSubmitResponse *, const char*);
SOAP_FMAC5 struct ns1__transferTaskAndSubmitResponse * SOAP_FMAC6 soap_new_ns1__transferTaskAndSubmitResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__transferTaskAndSubmitResponse(struct soap*, struct ns1__transferTaskAndSubmitResponse*);
SOAP_FMAC3 struct ns1__transferTaskAndSubmitResponse * SOAP_FMAC4 soap_instantiate_ns1__transferTaskAndSubmitResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__transferTaskAndSubmitResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__sendCommandType
#define SOAP_TYPE_PointerTons1__sendCommandType (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__sendCommandType(struct soap*, ns1__sendCommandType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__sendCommandType(struct soap*, ns1__sendCommandType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__sendCommandType(struct soap*, const char *, int, ns1__sendCommandType *const*, const char *);
SOAP_FMAC3 ns1__sendCommandType ** SOAP_FMAC4 soap_get_PointerTons1__sendCommandType(struct soap*, ns1__sendCommandType **, const char*, const char*);
SOAP_FMAC3 ns1__sendCommandType ** SOAP_FMAC4 soap_in_PointerTons1__sendCommandType(struct soap*, const char*, ns1__sendCommandType **, const char*);

#ifndef SOAP_TYPE_PointerTons1__transferTaskType
#define SOAP_TYPE_PointerTons1__transferTaskType (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__transferTaskType(struct soap*, ns1__transferTaskType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__transferTaskType(struct soap*, ns1__transferTaskType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__transferTaskType(struct soap*, const char *, int, ns1__transferTaskType *const*, const char *);
SOAP_FMAC3 ns1__transferTaskType ** SOAP_FMAC4 soap_get_PointerTons1__transferTaskType(struct soap*, ns1__transferTaskType **, const char*, const char*);
SOAP_FMAC3 ns1__transferTaskType ** SOAP_FMAC4 soap_in_PointerTons1__transferTaskType(struct soap*, const char*, ns1__transferTaskType **, const char*);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__integer(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__integer(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__integer(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
