/* soapServer.c
   Generated by gSOAP 2.7.9l from CRAB-Proxy.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.7.9l 2008-03-26 10:19:13 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:transferTaskAndSubmit"))
		return soap_serve_ns1__transferTaskAndSubmit(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:sendCommand"))
		return soap_serve_ns1__sendCommand(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getTaskStatus"))
		return soap_serve_ns1__getTaskStatus(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__transferTaskAndSubmit(struct soap *soap)
{	struct ns1__transferTaskAndSubmit soap_tmp_ns1__transferTaskAndSubmit;
	struct ns1__transferTaskAndSubmitResponse _param_1;
	soap_default_ns1__transferTaskAndSubmitResponse(soap, &_param_1);
	soap_default_ns1__transferTaskAndSubmit(soap, &soap_tmp_ns1__transferTaskAndSubmit);
	soap->encodingStyle = NULL;
	if (!soap_get_ns1__transferTaskAndSubmit(soap, &soap_tmp_ns1__transferTaskAndSubmit, "ns1:transferTaskAndSubmit", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__transferTaskAndSubmit(soap, soap_tmp_ns1__transferTaskAndSubmit.transferTaskAndSubmitRequest, &_param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__transferTaskAndSubmitResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__transferTaskAndSubmitResponse(soap, &_param_1, "ns1:transferTaskAndSubmitResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__transferTaskAndSubmitResponse(soap, &_param_1, "ns1:transferTaskAndSubmitResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__sendCommand(struct soap *soap)
{	struct ns1__sendCommand soap_tmp_ns1__sendCommand;
	struct ns1__sendCommandResponse _param_2;
	soap_default_ns1__sendCommandResponse(soap, &_param_2);
	soap_default_ns1__sendCommand(soap, &soap_tmp_ns1__sendCommand);
	soap->encodingStyle = NULL;
	if (!soap_get_ns1__sendCommand(soap, &soap_tmp_ns1__sendCommand, "ns1:sendCommand", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__sendCommand(soap, soap_tmp_ns1__sendCommand.sendCommandRequest, &_param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__sendCommandResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__sendCommandResponse(soap, &_param_2, "ns1:sendCommandResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__sendCommandResponse(soap, &_param_2, "ns1:sendCommandResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__getTaskStatus(struct soap *soap)
{	struct ns1__getTaskStatus soap_tmp_ns1__getTaskStatus;
	struct ns1__getTaskStatusResponse _param_3;
	soap_default_ns1__getTaskStatusResponse(soap, &_param_3);
	soap_default_ns1__getTaskStatus(soap, &soap_tmp_ns1__getTaskStatus);
	soap->encodingStyle = NULL;
	if (!soap_get_ns1__getTaskStatus(soap, &soap_tmp_ns1__getTaskStatus, "ns1:getTaskStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__getTaskStatus(soap, soap_tmp_ns1__getTaskStatus.getTaskStatusRequest, &_param_3);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__getTaskStatusResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getTaskStatusResponse(soap, &_param_3, "ns1:getTaskStatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getTaskStatusResponse(soap, &_param_3, "ns1:getTaskStatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapServer.c */
