USE mysql
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON boss_rt_v3_6.* TO 'BOSSv3_6manager'@localhost IDENTIFIED BY 'BossMySQL' WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON boss_rt_v3_6.* TO 'BOSSv3_6manager'@'cmsboui1.bo.infn.it' IDENTIFIED BY 'BossMySQL' WITH GRANT OPTION;
GRANT SELECT ON boss_rt_v3_6.* TO 'BOSSv3_6monitor'@localhost IDENTIFIED BY 'BossMySQL';
GRANT SELECT ON boss_rt_v3_6.* TO 'BOSSv3_6monitor'@'cmsboui1.bo.infn.it' IDENTIFIED BY 'BossMySQL';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON boss_rt_v3_6.* TO 'BOSSv3_6manager'@'%.bo.infn.it' IDENTIFIED BY 'BossMySQL' WITH GRANT OPTION;
GRANT SELECT ON boss_rt_v3_6.* TO 'BOSSv3_6monitor'@'%.bo.infn.it' IDENTIFIED BY 'BossMySQL';
CREATE DATABASE IF NOT EXISTS boss_rt_v3_6;
USE boss_rt_v3_6
CREATE TABLE BOSSRTMON (
RECORD              INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
USERID           VARCHAR(255) NOT NULL DEFAULT "N", 
DEST_CLIENT_ID   VARCHAR(36)  NOT NULL DEFAULT "NONE",
DEST_CLIENT_JOBID   INT  NOT NULL DEFAULT "NONE",
DEST_CLIENT_TABLE   VARCHAR(200)  NOT NULL DEFAULT "NONE",
DEST_CLIENT_COLUMN  VARCHAR(200)  NOT NULL DEFAULT ".",
DEST_CLIENT_VALUE   VARCHAR(255)  NOT NULL DEFAULT ".",
TIME_STAMP          INTEGER NOT NULL DEFAULT 0,
UNIQUE (DEST_CLIENT_ID,DEST_CLIENT_JOBID,DEST_CLIENT_TABLE,DEST_CLIENT_COLUMN)
);

FLUSH PRIVILEGES;
