#!/bin/sh

bossAdmin registerProgram -name condor_g -schema $CRABSCRIPT/condor_g.schema -pre $CRABSCRIPT/condor_g.preruntime -post $CRABSCRIPT/condor_g.runtime -runtime $CRABSCRIPT/condor_g.runtime -comment "Job submitted to OSG"
