#!/bin/sh

bossAdmin registerScheduler -name glitecoll -submit $CRABSCRIPT/glite_collSubmit.py -query $CRABSCRIPT/glite_query.py -kill $CRABSCRIPT/glite_kill.pl -getout $CRABSCRIPT/glite_getout.pl -job_id_env_var GLITE_WMS_JOBID -schema $CRABSCRIPT/schema -listMatch $CRABSCRIPT/glite_listMatch.pl $@
