#!/bin/sh

bossAdmin registerScheduler -name glite -submit $CRABSCRIPT/script/glite_submit.pl -query $CRABSCRIPT/script/glite_query.py -kill $CRABSCRIPT/script/glite_kill.pl -getout $CRABSCRIPT/script/glite_getout.pl -job_id_env_var GLITE_WMS_JOBID -schema $CRABSCRIPT/script/glite_schema


