#!/bin/sh

bossAdmin registerProgram -name glite -schema $CRABSCRIPT/edg.schema -pre $CRABSCRIPT/edg.preruntime -post $CRABSCRIPT/edg.runtime -runtime $CRABSCRIPT/edg.runtime -comment "Job submitted to LCG/GLite"
