#!/bin/sh

bossAdmin registerScheduler -name glite -submit $CRABSCRIPT/glite_submit.pl -query $CRABSCRIPT/glite_query.py -kill $CRABSCRIPT/glite_kill.pl -getout $CRABSCRIPT/glite_getout.pl -job_id_env_var GLITE_WMS_JOBID -schema $CRABSCRIPT/glite_schema


