#!/bin/sh

boss registerScheduler -name glite -submit $CRABSCRIPT/script/glite_submit.pl -query $CRABSCRIPT/script/glite_query.pl -kill $CRABSCRIPT/script/glite_kill.pl -getout $CRABSCRIPT/script/glite_getout.pl


