#!/bin/sh

boss showJobTypes | grep "ORCA_PUBDB job" > /dev/null
if [ $? -eq 0 ];then
 boss registerJob -name orca_PUBDB  -post $CRABSCRIPT/orca.runtime -runtime $CRABSCRIPT/orca.runtime -comment "ORCA_PUBDB job"
else
 boss registerJob -name orca_pubdb -schema $CRABSCRIPT/orca.schema -post $CRABSCRIPT/orca.runtime -runtime $CRABSCRIPT/orca.runtime -comment "ORCA_PUBDB job"
fi

boss showJobTypes | grep "ORCA job" > /dev/null
if [ $? -eq 0 ];then
 ## register without schema
 boss registerJob -name orca  -post $CRABSCRIPT/orca.runtime -runtime $CRABSCRIPT/orca.runtime -comment "ORCA job"
else
 ## first time: register with schema
 boss registerJob -name orca -schema $CRABSCRIPT/orca.schema -post $CRABSCRIPT/orca.runtime -runtime $CRABSCRIPT/orca.runtime -comment "ORCA job"
fi
