#!/bin/sh

bossAdmin registerScheduler -name condor_g -submit $BOSS_ROOT/BossSched/bin/condor_g_submit.pl -query $BOSS_ROOT/BossSched/bin/condor_g_query.py -kill $BOSS_ROOT/BossSched/bin/condor_g_kill.pl -getout $BOSS_ROOT/BossSched/bin/condor_g_getout.pl -topwdir . $@
