#!/bin/sh

boss registerScheduler -name condor -submit $CRABSCRIPT/condor_submit.pl -query $CRABSCRIPT/condor_query.pl -kill $CRABSCRIPT/condor_kill.pl -getout $CRABSCRIPT/condor_getout.pl -topwdir NONE
