#!/bin/sh

bossAdmin registerProgram -name crabjob -schema $CRABSCRIPT/crab.schema  -pre $CRABSCRIPT/crab.preruntime -post $CRABSCRIPT/crab.runtime -runtime $CRABSCRIPT/crab.runtime -comment "CRAB job"
