#!/bin/sh

boss registerScheduler -name fork -submit $CRABSCRIPT/fork_submit.pl -query $CRABSCRIPT/fork_query.pl -kill $CRABSCRIPT/fork_kill.pl -getout $CRABSCRIPT/fork_getout.pl -default -topwdir . -cpComm cp -cpWNPref . -cpRemPref "\$PWD"
