#! /bin/sh
#
# Installation script for Crab
#

# Subdir structure:
#     Boss/...
#     python/...
#     script/...
#     DBSAPI
#     DLSAPI
#     PsetCode
#

# TopDir = CRAB/python
TopDir=`\pwd`

#############################################
######## BOSS CONFIGURATION #################
#############################################

## to change the BOSSVER value with the BOSS version you want to use.
## Check if the version of BOSS you want to use exists on BOSS homepage ... 
BOSSVER=4_0_0

BACKEND=SQLite

function configureBoss {
## unpack and configure Boss

if [ ! -d ../Boss ] ;then 
   mkdir ../Boss
   result=$?
   if [ $result != 0 ] ;then
      echo "problem with ../Boss dir creation"
      exit
   fi  
else
   echo "directory ../Boss exists"
fi

if [ ! -s ../Boss/boss-v${BOSSVER}-bin.tar.gz ] ;then
   cd ../Boss
#   WARNING:
#   wget http://boss.bo.infn.it/boss-v${BOSSVER}-bin.tar.gz
   cp /afs/cern.ch/user/f/fanzago/public/boss-v${BOSSVER}-bin.tar.gz .
   result=$?
   if [ $result != 0 ] ;then
      echo "problem with boss tgz download"
      exit
   fi
else
   echo "boss-v${BOSSVER}-bin.tar.gz already downloaded"
fi 

cd ../Boss
if [ ! -d BOSS ] ;then
   if [ ! -d boss-v${BOSSVER} ] ;then
      echo "unpacking BOSS distribution ${BOSSVER}"
      tar xzf boss-v${BOSSVER}-bin.tar.gz
   fi
   if [ -d boss-v${BOSSVER} ] ;then
      mv boss-v${BOSSVER} BOSS
      ls
   fi   

   cd BOSS

   echo "Creating Env. files"
   source install.sh
   echo "Creating ./BossConfig.clad"
   cat > ./BossConfig.clad <<EOF
# This is the BOSS configuration file

[
# BOSS temporary directory (where files are extracted from DB)
BOSS_TMP_DIR = "/tmp";

# BOSS update interval
BOSS_MIN_UPD_INT = 30;  # at most one upd. every BOSS_MIN_UPD_INT sec.
BOSS_MAX_UPD_INT = 180; # at least one upd. every BOSS_MAX_UPD_INT sec.

# Maximum retries after post-process finishes before killing RTUpdator
# (waits BOSS_UPD_INTERVAL*BOSS_MAX_RETRY seconds)
BOSS_MAX_RETRY = 3;

# Boss Database Backend
DB_BACKEND = "${BACKEND}";

# Info sent also to Monalisa (if empty not enabled)
ML_URL = "";
]
EOF

   echo "Setting environment"
   source bossenv.sh
   which boss
else
   echo "../Boss/BOSS already exists"
   which boss
   result=$?
   if [ $result != 0 ] ;then
      source ../Boss/BOSS/bossenv.sh  
   fi
   echo "boss: "
   which boss
fi

}

function configureCrab {
## prapare the crab env
cd $TopDir

# sh style
cat > crab.sh <<EOF
#! /bin/sh
# CRAB related Stuff
export CRABDIR=$TopDir/..
export CRABSCRIPT=\${CRABDIR}/script

CRABPATH=\${CRABDIR}/python
CRABDLSAPIPATH=\${CRABDIR}/DLSAPI
export CRABPYTHON=\${CRABDIR}/python
export CRABDBSAPIPYTHON=\${CRABDIR}/DBSAPI
export CRABDLSAPIPYTHON=\${CRABDIR}/DLSAPI
export CRABPSETPYTHON=\${CRABDIR}/PsetCode

if [ -z "\$PATH" ]; then
export PATH=\${CRABPATH}:\${CRABDLSAPIPATH}
else
export PATH=\${CRABPATH}:\${PATH}:\${CRABDLSAPIPATH}
fi
if [ -z "\$PYTHONPATH" ]; then
export PYTHONPATH=\${CRABPYTHON}:\${CRABDBSAPIPYTHON}:\${CRABDLSAPIPYTHON}:\${CRABPSETPYTHON}
else
export PYTHONPATH=\${CRABPYTHON}:\${PYTHONPATH}:\${CRABDBSAPIPYTHON}:\${CRABDLSAPIPYTHON}:\${CRABPSETPYTHON}
fi

# BOSS related Stuff
source $BOSS_ROOT/bossenv.sh

# check whether central boss db is configured

# check if .bossrc dir exists

if [ ! -d ~/.bossrc ]; then
  mkdir ~/.bossrc
fi

# check if *clad files exist

if [ ! -e ~/.bossrc/BossConfig.clad ]; then
  if [ -e ~/BossConfig.clad ]; then
    cp  ~/BossConfig.clad ~/.bossrc/BossConfig.clad
  else
    echo "User-boss DB not installed: run configureBoss"
    return 1
  fi
fi
if [ ! -e ~/.bossrc/SQLiteConfig.clad ]; then
  if [ -e ~/SQLiteConfig.clad ]; then
    cp ~/SQLiteConfig.clad ~/.bossrc/SQLiteConfig.clad
  else
    echo "User-boss DB not installed: run configureBoss"
    return 1
  fi
fi
if [ ! -e ~/.bossrc/MySQLRTConfig.clad ]; then
  if [ -e ~/MySQLRTConfig.clad ]; then
    cp  ~/MySQLRTConfig.clad  ~/.bossrc/MySQLRTConfig.clad
  else
    echo "User-boss DB not installed: run configureBoss"
    return 1
  fi
fi
# now check a boss command to see if boss DB is up and running
if [ \`boss clientID 1>/dev/null | grep -c "not correctly configured"\` -ne 0 ]; then
  echo "User-boss DB not installed: run configureBoss"
    return 1
fi
EOF

# csh style
cat > crab.csh <<EOF
#! /bin/csh
# CRAB related Stuff
setenv CRABDIR $TopDir/..
setenv CRABSCRIPT \${CRABDIR}/script

set CRABPATH=\${CRABDIR}/python
set CRABDLSAPIPATH=\${CRABDIR}/DLSAPI
setenv CRABPYTHON \${CRABDIR}/python
setenv CRABDBSAPIPYTHON \${CRABDIR}/DBSAPI
setenv CRABDLSAPIPYTHON \${CRABDIR}/DLSAPI
setenv CRABPSETPYTHON \${CRABDIR}/PsetCode

if ( ! \$?path ) then
set path=(\${CRABPATH} \${CRABDLSAPIPATH})
else
set path=( \${CRABPATH} \${path} \${CRABDLSAPIPATH})
endif
if ( ! \$?PYTHONPATH ) then
setenv PYTHONPATH \${CRABPYTHON}:\${CRABDBSAPIPYTHON}:\${CRABDLSAPIPYTHON}:\${CRABPSETPYTHON}
else
setenv PYTHONPATH \${CRABPYTHON}:\${PYTHONPATH}:\${CRABDBSAPIPYTHON}:\${CRABDLSAPIPYTHON}:\${CRABPSETPYTHON}
endif

# BOSS related Stuff
source $BOSS_ROOT/bossenv.csh

# check whether central boss db is configured

# check if .bossrc dir exists

if ( ! -d ~/.bossrc ) then
  mkdir ~/.bossrc
endif

# check if *clad files exist
if ( ! -e ~/.bossrc/BossConfig.clad ) then
  if ( -e ~/BossConfig.clad ) then
    cp ~/BossConfig.clad ~/.bossrc/BossConfig.clad
  else
    echo "User-boss DB not installed: run configureBoss"
    exit 1
  endif
endif
if ( ! -e ~/.bossrc/SQLiteConfig.clad ) then
  if ( -e ~/SQLiteConfig.clad ) then
    cp ~/SQLiteConfig.clad ~/.bossrc/SQLiteConfig.clad
  else
    echo "User-boss DB not installed: run configureBoss"
    exit 1
  endif
endif
if ( ! -e ~/.bossrc/MySQLRTConfig.clad ) then
  if ( -e ~/MySQLRTConfig.clad ) then
    cp ~/MySQLRTConfig.clad  ~/.bossrc/MySQLRTConfig.clad
  else
    echo "User-boss DB not installed: run configureBoss"
    exit 1
  endif
endif
# now check a boss command to see if boss DB is up and running
if ( \`boss clientID |& grep -c "not correctly configured"\` ) then
  echo "User-boss DB not installed: run configureBoss"
  exit 1
endif
EOF
return
}

function configureDLSAPI {
# part for PyXML install
echo "DLSAPI Installation: begin at `date`"
cd $TopDir/DLSAPI
./InstallPyXML.sh
cd ..
echo "DLSAPI Installation: end at `date`"
return
}

configureBoss
configureCrab
#configureDLSAPI

