#!/usr/bin/env sh
#
# 07-Dec-2005
# Stefano Lacaprara  <lacaprara@pd.infn.it>  INFN Padova
#
# Wrapper script for crab.py
#
if [ -z "$PYTHONPATH" ]; then
  export PYTHONPATH=${CRABDBSAPIPYTHON}:${CRABDLSAPIPYTHON}:${CRABPSETPYTHON}:${CRABPYTHON}
else
  export PYTHONPATH=${CRABDBSAPIPYTHON}:${CRABDLSAPIPYTHON}:${CRABPSETPYTHON}:${PYTHONPATH}:${CRABPYTHON}
fi
#echo $PYTHONPATH

export LD_LIBRARY_PATH=${GLITE_LOCATION}/lib:${LD_LIBRARY_PATH}

# echo $LD_LIBRARY_PATH
# ldd `which voms-proxy-info`


#if [ -z "$CMSSW_VERSION" ]; then
#  echo ''
#  echo 'crab Error: Could not find CMSSW environment' 
#  echo '      Please before use crab setup:' 
#  echo '      eval `scramv1 runtime -c|sh` ' 
#else
# prepare the environment # Fabio
#  eval `python $CRABPYTHON/unfoldEnv.py $*`
#  
  #/usr/bin/env python $CRABPYTHON/crab.py $*
  python $CRABPYTHON/crab.py $*
#fi

