#!/bin/bash

crabDir=$1
bossDir=$2
dest=$3

echo $crabDir, $bossDir, $dest
mkdir $dest
mkdir $dest/bin
mkdir $dest/lib
mkdir $dest/python
mkdir $dest/script

# copy bin
cp $bossDir/bin/* $dest/bin/.
ln -s $crabDir/python/crab.py $dest/bin/.

# copy lib
cp $bossDir/lib/*.so* $dest/lib/.
#cp $bossDir/log4cplus/lib/*.so* $dest/lib/.
cp $bossDir/mysql/lib/*.so* $dest/lib/.
cp $bossDir/sqlite/lib/*.so* $dest/lib/.

# copy python
cp $crabDir/python/* $dest/python/.

# copy script
cp $crabDir/python/BossScript/* $dest/script/.

# create configure
cp $crabDir/python/configure* $dest/.


